

function MakeNounVerbNounBook() {
	return GetRand(adjectives) + " " + GetRand(nouns) + " " + GetRand(ObjectVerbs) + " The " + GetRand(adjectives) + " " + GetRand(nouns);
}

function MakeNounNounVerbBook() {
	return GetRand(adjectives) + " " + GetRand(nouns) + " And " + GetRand(adjectives) + " " + GetRand(nouns) + " " + GetRand(ReflexiveVerbs);
}

function MakeAdjAdjAdjNoun() {
	return GetRand(adjectives) + ", " + GetRand(adjectives) + ", and " + GetRand(adjectives) + " " + GetRand(nouns);
}

function MakeNounNounNounVerb() {
	return GetRand(nouns) + ", " + GetRand(nouns) + ", and " + GetRand(nouns) + " " + GetRand(ReflexiveVerbs);
}

function MakeNounIsAdj() {
	return GetRand(nouns) + " is " + GetRand(adjectives);
}

function makeRandomBook() {
	var rVal = Math.random();
	if (rVal < 0.4) {
		return GetRand(booktitles);
	}
	if (rVal < 0.55) {
		return MakeNounVerbNounBook();
	}
	if (rVal < 0.7) {
		return MakeNounNounVerbBook();
	}
	if (rVal < 0.8) {
		return MakeAdjAdjAdjNoun();
	}
	if (rVal < 0.9) {
		return MakeNounNounNounVerb();
	}
	return MakeNounIsAdj();
}

function createBookNames(numberOfBooks) {
	var ourSet = new Set();
	while (ourSet.size < numberOfBooks) {
		ourSet.add(makeRandomBook());
	}
	return [...ourSet].sort();
}

var booktitles = ["Ancient Mage Wife",
"Aaronson's Bizzare Adventrue",
"Leaf's Library",
"Bouqet Balances Ballet",
"Airons Arithmetic",
"Ututu's Time Integrators",
"Ahia's Hash",
"Bouquet's Moment (of Inertia)",
"Ahia Is Not a Ghost",
"Leaf's Sorted Story",
"Quinn Won't Quit",
"A Stroll Through Cecily's Sets",
"Ackermann Escapes The Primitives",
"Amanda Automates",
"Arthur Merlin Games",
"Ben's Binary Basics",
"Bounded By Space",
"Busy Beavers",
"BOGO Sort And Other Bad Algorithms",
"Cecily's Complex Theory",
"Cellular Automation",
"Choosing Choice",
"Church Turing Thesis",
"Complexity Zoo",
"Counting Above the Hierarchy",
"Descending Grades While Deep Learning?!",
"Dynamic Programming",
"Older Scrolls V: Print Edition",
"Error Correction: The Code",
"Expanding Graphs",
"Following The First Order's Logic",
"Fourier's Fast Transformation",
"Gentle Measurements",
"Halting Problems?",
"Henry's Heuristics Help",
"Hermit's Singular Value",
"How to Salt Your Hash",
"In The Density Matrix",
"Interaction During Proofs",
"It's polynomial time",
"Just in Time for Execution",
"Kernel Panic",
"Lazy Loaders",
"Lily Learns Lists",
"Lily Likes Logic",
"Locked Threads",
"Markov's Chains",
"Min Cuts For Max Flow",
"Nick's Class",
"No Witnesses Without Collapse",
"Oracles of Separation",
"PCP, a local problem",
"Pigeon Hole Principles",
"Problems on Promises",
"Pseudo-telepathy",
"Quackack: The Sound of a Speaker With a Duck Bill Taped to it.",
"Quinn's Quantum Query",
"Raven Researches Randomness",
"Removing Randomness is Hard!",
"Satisfying Your Circuits",
"Seth, are you too strong?",
"Sexadecimal, and Other Radixal Ideas",
"Space and Time Hierarchies",
"Spooky Action With Teams",
"Stop Repeating Yourself and Memoize",
"Superdense Coders",
"Switching Lemmas For Shorter Trees",
"Thresholds Multiplying",
"Too Much Red In my Black Tree: A Shift In Balance",
"Trap Doors For Privacy",
"Trusted Advice for All Situations",
"Trading Time for Space",
"Undirected Paths In The Log Space",
"Virtually Machines and Virtually Reality",
"Witness",
"XOR",
"You Complete Me (and that's what makes this hard)",
"Zero Knowledge in Proofs, Statistically",
"Adventure Rhyme",
"Ghouls and Goods",
"Help, I'm Not a Book",
"Ladies Love",
"Lock Looks",
"Automatic Hugs",
"Fates Shook",
"Toasted Tots",
"Bloated Bots",
"Roots with Rots",
"Local Lots",
"Comfy Cots",
"Quantum Quips",
"Whirly Whips",
"Hoppy Hips",
"Sweet Sips",
"Ballet Feet",
"The Underneath",
"Gear Teeth!",
"Discrete Peak",
"Quantum Leak",
"Bots Battling in Lots",
"Data Bleach",
"Manico",
"Fairy Feuds",
"Fairy Fords",
"Fae Wards",
"Fae Doors",
"Spirits of The Seasons",
"Flowers as Medicine",
"The Beautiful Hour",
"Few Fast Friends"];

var nouns = ["Apple",
		"Ant",
		"Amy",
		"Bat",
		"Ahia",
		"Bannana",
		"Boss",
		"Bird",
		"Butterfly",
		"Bouquet",
		"Cat",
		"Carrot",
		"Chalk",
		"Candy",
		"Dingbat",
		"Dude",
		"Diamond",
		"Dragon",
		"Duck",
		"Donut",
		"Dog",
		"Elephant",
		"Egg",
		"Ezekial",
		"Fairy",
		"Fish",
		"Fae",
		"Frog",
		"Food",
		"Gold",
		"Gnome",
		"Gobblin",
		"Ghoul",
		"Ghost",
		"Goo",
		"Gravy",
		"Honey Suckle",
		"Helpers",
		"Heart",
		"Hood",
		"Home",
		"Hyena",
		"Interior",
		"Ice Cream",
		"Igloo",
		"Iguana",
		"Jim",
		"Jack-O'-Lanturn",
		"Jerky",
		"Kid",
		"Kite",
		"King",
		"Light",
		"Ladie",
		"Lad",
		"Leaf",
		"Lavender Meadow",
		"Lesson",
		"Lemon",
		"Lemur",
		"Moment",
		"Moon",
		"Mime",
		"Minnow",
		"Mouse",
		"Monkey",
		"Mermaid",
		"Niece",
		"Neighbor",
		"Nest",
		"Obstacle",
		"Orangutane",
		"Orange",
		"Prince",
		"Princess",
		"Price",
		"Person",
		"Pickle",
		"Platypus",
		"Queen",
		"Query",
		"Quail",
		"Quest",
		"Rake",
		"Rail",
		"Rule",
		"Royalty",
		"Spirit",
		"Suit",
		"Song",
		"Salad",
		"Star",
		"Sun",
		"Theif",
		"Teacher",
		"Torch",
		"Tinsel",
		"Tree",
		"Time",
		"Umbrella",
		"Unicorn",
		"Vortex",
		"Vince",
		"Wizard",
		"Will-O'-Wisp",
		"Water",
		"Xenon",
		"Yack",
		"Zebra",
		"Zealot"];

var adjectives = ["Amazing",
"Angry",
"Aquatic",
"Barbaric",
"Beautiful",
"Brave",
"Blue",
"Bold",
"Brown",
"Bitter",
"Burning",
"Black",
"Big",
"Bright",
"Brittle",
"Bored",
"Courageous",
"Colorful",
"Cold",
"Chilly",
"Cyan",
"Cute",
"Dizzy",
"Digital",
"Dry",
"Dark",
"Durable",
"Doomed",
"Digging",
"Evil",
"Electronic",
"Enchanted",
"Embarressed",
"Fabled",
"Firey",
"Flying",
"Fast",
"Foolish",
"Fantastic",
"Good",
"Gray",
"Goofy",
"Greedy",
"Green",
"Healthy",
"Hot",
"Horrible",
"Hidden",
"Happy",
"Hard",
"Hungry",
"Hairy",
"Huge",
"Ingenious",
"Icy",
"Jaded",
"Joyful",
"Knowledgable",
"Lazy",
"Lovely",
"Little",
"Magic",
"Magical",
"Mysterious",
"Noble",
"Naked",
"Open",
"Old",
"Pious",
"Poor",
"Proud",
"Pretty",
"Purple",
"Pink",
"Pastel",
"Quirky",
"Queer",
"Quantum",
"Reasonable",
"Red",
"Rich",
"Spooky",
"Sparkly",
"Shiney",
"Stable",
"Scary",
"Scared",
"Shy",
"Sad",
"Sick",
"Slimey",
"Suspicious",
"Slow",
"Soft",
"Surprised",
"Sleepy",
"Small",
"Sweet",
"Salty",
"Sour",
"Savory",
"Space",
"Strong",
"Twinkling",
"Thankful",
"Tiny",
"Tall",
"Tired",
"Talented",
"Ugly",
"Unending",
"Valuable",
"Vigilant",
"Violet",
"Virtual",
"Warm",
"Weird",
"Wise",
"Weak",
"White",
"Wet",
"Worried",
"Exciting",
"Extreme",
"Yodelling",
"Young",
"Zany"];

var ObjectVerbs = ["Attacks",
"And",
"Aids",
"Burdens",
"Buys",
"Buries",
"Curses",
"Cures",
"Casts A Spell On",
"Dates",
"Dumps",
"Dislikes",
"Eats",
"Elects",
"Enjoys",
"Forgets",
"Feeds",
"Frolics With",
"Feels",
"Greets",
"Helps",
"Heals",
"Honor",
"Hurts",
"Ignites",
"Irritates",
"Ignores",
"Juices",
"Jokes With",
"Joins",
"Jumps Over",
"Keeps",
"Kisses",
"Limits",
"Mimics",
"Marries",
"Needs",
"Pleases",
"Pranks",
"Plays a Trick on",
"Raises",
"Runs From",
"Steals",
"Scratches",
"Soothes",
"Stimulates",
"Seals",
"Saves",
"Takes",
"Teaches",
"Undermines",
"Wins",
"Won't Talk To",
"With",
"Watches",
"Zaps"];

var ReflexiveVerbs = ["Agree",
"Battle",
"Collude",
"Cook",
"Cry",
"Chill",
"Dine",
"Elope",
"Fly",
"Are Faries",
"Flee",
"Help",
"Hide",
"Hear",
"Itch",
"Jump",
"Jam",
"Lose",
"Love",
"Open",
"Play",
"Practice",
"Run",
"Race",
"Riot",
"Get Revenge",
"Are Rivals",
"Sleep",
"Sing",
"Swim",
"Swell",
"Smile",
"Sneak",
"Steal",
"Teleport",
"Talk",
"Trip",
"Wait"];